apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jta-gateway
  namespace: jta
spec:
  parentRefs:
  - name: gateway-external
    namespace: gateway
    sectionName: auburntech-net
  hostnames:
  - "jta.auburntechconsulting.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: wordpress-service
      port: 80
