apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jta-mysql
  labels:
    app: jta-mysql
  namespace: jta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jta-mysql
  template:
    metadata:
      labels:
        app: jta-mysql
    spec:
      containers:
      - name: jta-mysql
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        envFrom:
          - secretRef:
              name: mysql-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
          - name: mysql-data
            persistentVolumeClaim:
              claimName: jta-db-nfs-pvc