apiVersion: v1
kind: Service
metadata:
  name: codeproject-ai
  namespace: ai
spec:
  type: ClusterIP
  selector:
    app: codeproject-ai
  ports:
  - port: 32168
    targetPort: 32168
    protocol: TCP