apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: auburntech-gateway
  namespace: auburntech-dmz
spec:
  parentRefs:
    - name: gateway-external
      namespace: gateway
  hostnames:
    - "auburntechconsulting.com"
    - "www.auburntechconsulting.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: auburntech
          port: 8080