apiVersion: apps/v1
kind: Deployment
metadata:
  name: sterlingpdf
  namespace: pdf
spec:
  selector:
    matchLabels:
      app: sterlingpdf
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sterlingpdf
    spec:
      containers:
      - name: sterlingpdf
        image: frooodle/s-pdf:2.4.5
        resources:
          requests:
            cpu: "10m"
            memory: "200Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        env:
            - name: SECURITY_ENABLE_LOGIN
              value: "false"
        volumeMounts:
            - mountPath: /configs
              name: sterlingpdf-data
        ports:
        - containerPort: 8080
      volumes:
        - name: sterlingpdf-data
          emptyDir: {}