apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: internal-enforce-max-body-size
  namespace: gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway-local-koryalbert
  body:
    maxSize: 10g