apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  generation: 1
  name: gateway-client-settings
  namespace: gateway
  resourceVersion: "74867315"
  uid: 5a804167-710b-4383-931a-a7b4ace33c8f
spec:
  body:
    maxSize: 5g
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway-external