apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trustedtable-app
  name: trustedtable-app
  namespace: trustedtable
spec:
  selector:
    matchLabels:
      app: trustedtable-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 0
     maxSurge: 2
  template:
    metadata:
      labels:
        app: trustedtable-app
    spec:
      containers:
        - name: trustedtable-app
          image: php:8.2.28-apache
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: trustedtable
          ports:
            - containerPort: 80
              name: website-port
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: website-port
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              path: /
              port: website-port
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 5
          resources:
            requests:
              cpu: 20m
              memory: 40Mi
            limits:
              cpu: 100m
              memory: 150Mi
          volumeMounts:
            - mountPath: /var/www/html
              name: trustedtable-data
      volumes:
        - name: trustedtable-data
          nfs:
            server: 192.168.2.252
            path: "/mnt/tank/nfs/Websites/trustedtable"
            readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trustedtable-api
  name: trustedtable-api
  namespace: trustedtable
spec:
  selector:
    matchLabels:
      app: trustedtable-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 0
     maxSurge: 2
  template:
    metadata:
      labels:
        app: trustedtable-api
    spec:
      containers:
        - name: trustedtable-api
          image: public.ecr.aws/b7c8g1g5/linuxeclipsed/trustapi:dev
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: trustedtable
          ports:
            - containerPort: 8000
              name: api-port
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trustedtable-image-api
  name: trustedtable-image-api
  namespace: trustedtable
spec:
  selector:
    matchLabels:
      app: trustedtable-image-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 0
     maxSurge: 2
  template:
    metadata:
      labels:
        app: trustedtable-image-api
    spec:
      containers:
        - name: trustedtable-image-api
          image: public.ecr.aws/b7c8g1g5/linuxeclipsed/image-api:dev
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: trustedtable
          ports:
            - containerPort: 8000
              name: api-port
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 8000
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
          volumeMounts:
            - mountPath: /app/images
              name: trustedtable-data
      volumes:
        - name: trustedtable-data
          nfs:
            server: 192.168.2.252
            path: "/mnt/tank/nfs/Websites/trustedtable/images"