apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: trustedtable-gateway
  namespace: trustedtable
spec:
  parentRefs:
  - name: gateway-external
    namespace: gateway
    sectionName: trustedtable-app
  hostnames:
  - "trustedtable.app"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: trustedtable-app
      port: 8080