apiVersion: v1
data:
  dbname: dHJ1c3RlZHRhYmxl
  host: cGdjbHVzdGVyLXRydXN0ZWR0YWJsZS1ydw==
  jdbc-uri: amRiYzpwb3N0Z3Jlc3FsOi8vcGdjbHVzdGVyLXRydXN0ZWR0YWJsZS1ydy50cnVzdGVkdGFibGU6NTQzMi90cnVzdGVkdGFibGU/cGFzc3dvcmQ9WDFBN1djd0ZQREZ4VG1PdDI1N2lYTkRuOFhma1prQ1pDVDRla2dmdFp3VW03QllZS1JUb0hUWEdpMEVlcDlDcSZ1c2VyPWFwcA==
  password: WDFBN1djd0ZQREZ4VG1PdDI1N2lYTkRuOFhma1prQ1pDVDRla2dmdFp3VW03QllZS1JUb0hUWEdpMEVlcDlDcQ==
  pgpass: cGdjbHVzdGVyLXRydXN0ZWR0YWJsZS1ydzo1NDMyOnRydXN0ZWR0YWJsZTphcHA6WDFBN1djd0ZQREZ4VG1PdDI1N2lYTkRuOFhma1prQ1pDVDRla2dmdFp3VW03QllZS1JUb0hUWEdpMEVlcDlDcQo=
  port: NTQzMg==
  uri: cG9zdGdyZXNxbDovL2FwcDpYMUE3V2N3RlBERnhUbU90MjU3aVhORG44WGZrWmtDWkNUNGVrZ2Z0WndVbTdCWVlLUlRvSFRYR2kwRWVwOUNxQHBnY2x1c3Rlci10cnVzdGVkdGFibGUtcncudHJ1c3RlZHRhYmxlOjU0MzIvdHJ1c3RlZHRhYmxl
  user: YXBw
  username: YXBw
kind: Secret
metadata:
  labels:
    cnpg.io/cluster: pgcluster-trustedtable
    cnpg.io/reload: "true"
    cnpg.io/userType: app
  name: pgcluster-trustedtable-app
  namespace: trustedtable
type: kubernetes.io/basic-auth
