apiVersion: v1
kind: Service
metadata:
  name: trustedtable-app-svc
  namespace: trustedtable
spec:
  ports:
    - port: 80
  selector:
    app: trustedtable-app
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: trustedtable-api-svc
  namespace: trustedtable
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: trustedtable-api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: trustedtable-image-api-svc
  namespace: trustedtable
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: trustedtable-image-api
  type: ClusterIP