apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik-gateway
  namespace: authentik-dmz
spec:
  parentRefs:
    - name: gateway-external
      namespace: gateway
  hostnames:
    - "authentik.koryalbert.net"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: my-authentik-server
          port: 80