apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-uploads-pvc
  namespace: immich
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-client
  resources:
    requests:
     storage: 5Gi